### ISSUE TITLE
Research: APIs or Data Sources for School Rankings

### ISSUE THREAD

**Issue by giladthe1st** [giladthe1st/moneytoba#6]
# Research: APIs or Data Sources for School Rankings in Winnipeg, Manitoba, Canada

## Objective
Identify and evaluate potential APIs or data sources that can be used to display a list of schools and kindergartens based on rankings in Winnipeg, Manitoba, Canada.

## Tasks
- [ ] Research available APIs for school data in Winnipeg
- [ ] Identify reliable data sources for school rankings
- [ ] Evaluate the quality and comprehensiveness of each source
- [ ] Check for any usage restrictions or costs associated with the APIs/data sources

## Findings
(To be filled in with research results)

### API/Data Source 1
- Name:
- URL:
- Description:
- Data provided:
- Ranking criteria (if available):
- Coverage (schools/kindergartens):
- Ease of use:
- Limitations:
- Cost/Usage restrictions:

### API/Data Source 2
(Repeat structure for each additional source found)
